# Generated by Django 4.1.7 on 2023-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('dispersion', models.DecimalField(decimal_places=3, max_digits=8)),
                ('right_ascension', models.DecimalField(decimal_places=3, max_digits=6)),
                ('declination', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
